// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // REMPLACEZ CES VALEURS PAR CELLES DE VOTRE CONSOLE FIREBASE SI FLUTTERFIRE ECHOUE
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtblSuapG-FQLy-xUK2xd4bTrWKzt93fc',
    appId: '1:875607847316:web:87f312baa6b0d471dfdf81',
    messagingSenderId: '875607847316',
    projectId: 'selton-25f38',
    authDomain: 'selton-25f38.firebaseapp.com',
    storageBucket: 'selton-25f38.firebasestorage.app',
    measurementId: 'G-H7VMTB8BKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtblSuapG-FQLy-xUK2xd4bTrWKzt93fc',
    appId: 'REMPLACER_PAR_VOTRE_APP_ID_ANDROID', // <--- À RECUPERER SUR LA CONSOLE POUR ANDROID
    messagingSenderId: '875607847316',
    projectId: 'selton-25f38',
    storageBucket: 'selton-25f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtblSuapG-FQLy-xUK2xd4bTrWKzt93fc',
    appId: 'REMPLACER_PAR_VOTRE_APP_ID_IOS', // <--- À RECUPERER POUR IOS
    messagingSenderId: '875607847316',
    projectId: 'selton-25f38',
    storageBucket: 'selton-25f38.firebasestorage.app',
    iosBundleId: 'com.example.seltonHotel',
  );
}
